### ISSUE TITLE
Improvements to bibtex parser

### ISSUE THREAD

**Issue by hturner** [Abhi-1U/rebib#4]
I think the bibtex parse can be improved by extracting all the information in the `newblocks`, then splitting out the year any URL. E.g.

    \bibitem[Bivand et~al.(2008)Bivand, Pebesma, and Gomez-Rubio]{sp}
    R.~S. Bivand, E.~J. Pebesma, and V.~Gomez-Rubio.
    \newblock \emph{Applied Spatial Data Analysis with {R}}.
    \newblock Springer, NY, 2008.
    \newblock URL \url{http://www.asdar-book.org/}.  

would become

    @book{sp,
    author = { R.~S. {Bivand, E.~J. Pebesma, and V.~Gomez-Rubio.} },
    publisher = {  \emph{Applied Spatial Data Analysis with {R}}.
    \newblock Springer, NY},
    year = {2008},
    url = {http://www.asdar-book.org/}
    }
    
You can remove the \newblock command, but it doesn't seem to do any harm. Note that there should be no punctuation or white space at the end of the publisher field. Since the capitalization of the publisher field is not altered, we don't need double braces here. The reason for separating out the year is to get a full stop afterwards - this may not be necessary depending on the bibstyle. The url field should not have any leading/trailing punctuation or white space. 

Authors are tricky because we need to enable the bib style to order by the first surname (or surname-like word) but allow for hand-edited bbl. So the left brace should go before the word used for ordering. I think this regex will do it:

    gsub("([^a-z]*)([A-Z])([^.].*)", "\\1{\\2\\3}", txt)
    
This works for some tricky cases, e.g. `"P.K.~Seidelmann~(Editor)."`, `"D.~W\"urtz and Y.~Chalabi with contribution from M.~Maechler, J.W.~Byers, and others."`, `"R.~S. von Bivand, E.~J. Pebesma, and V.~Gomez-Rubio."` (last one made up!).

**Comment by Abhi-1U** [comment]
Thanks for the constructive feedback,

I have done some work to implement URL as of now (arguably with some bugs),
though it still requires a little bit of polishing, improving how authors are handled 
and fixing where the double quotes are generated.

The bibliography toolkit has been spun off into a separate package, for the following reasons:

1. Eases managing other aspects of texor project
2. Opens up to experimentation of features.
3.  A repo to try out deploying pkg_down and other documentation to get some experience. 

feel free to try out the conversion process (for bibliography)

**Comment by hturner** [comment]
Thanks. I have had a look. I made a pull request to make the minor change to how braces are added to the author field. It looks like you are doing a great job at pulling out the year, URL and ISBN. But I still think it would be better to keep the formatting for the title/publication title. That is is because the formatting is different for different bib types, but we are always using book. E.g. titles of journal papers should not be in italics, but the journal name should be.

I think what it would be good to aim for is for all blocks between authors and URL (if any), to be put in the publisher field (unlike the title field, this respects formatting), then anything else would become a note (assuming year and ISBN are extracted similar to now). E.g.

    \bibitem[Limas et~al.(2007)Limas, Joaquín B. Ordieres~Meré, de~Pisón~Ascacibar,
      Espinoza, and Elías]{AMORE}
    M.~C. Limas, E.~P. V.~G. Joaquín B. Ordieres~Meré, F.~J.~M. de~Pisón~Ascacibar,
      A.~V.~P. Espinoza, and F.~A. Elías.
    \newblock \emph{AMORE: A MORE Flexible Neural Network Package}, 2007.
    \newblock URL
      \url{http://wiki.r-project.org/rwiki/doku.php?id=packages:cran:amore}.
    \newblock R package version 0.2-11.

would become

    @book{AMORE,
    author = {M.~C. {Limas, E.~P. V.~G. Joaquín B. Ordieres~Meré, F.~J.~M. de~Pisón~Ascacibar, A.~V.~P. Espinoza, and F.~A.  Elías}},
    publisher = {\emph{AMORE: A MORE Flexible Neural Network Package}},
    year = {2007},
    url = {http://wiki.r-project.org/rwiki/doku.php?id=packages:cran:amore},
    note = {R package version 02-11}
    }
    
Note this is the default citation format for a package (author, title, year, url and note), so it would be good to get this right.

Another example

    \bibitem[Venables and Ripley(2002)]{Venables:2002}
    W.~Venables and B.~Ripley.
    \newblock \emph{Modern Applied Statistics with S}.
    \newblock Springer, New York, fourth edition, 2002.
    \newblock URL \url{http://www.stats.ox.ac.uk/pub/MASS4}.
    \newblock ISBN 0-387-95457-0.

    @book{Venables:2002,
    author = {W.~{Venables and B.~Ripley}},
    publisher = {\emph{Modern Applied Statistics with S}. Springer, New York, fourth edition},
    year = {2002},
    url = {http://www.stats.ox.ac.uk/pub/MASS4},
    isbn = {0-387-95457-0}
    }

Only trailing punctuation should be removed, i.e. any period or comma at the end, not in the middle of a string. So probably trim trailing white space first, then remove any remaining period or comma.

**Comment by Abhi-1U** [comment]
I think currently the title is handled in an expected manner hence closing this issue.
